# パッチバージョン変更時のみ自動マージするワークフロー
name: Auto Patch Merge
on: pull_request
jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }} # Dependabotのプルリクエストのみ
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: dependabot/fetch-metadata@v2
      - if: ${{ steps.meta.outputs.update-type == 'version-update:semver-patch' }} # パッチバージョン変更時のみ
        run: echo "Patch version change detected"
      # 8-6
      # - if: ->
      #     ${{ steps.meta.outputs.dependency-type == 'direct:development' &&
      #         steps.meta.outputs.update-type != 'version-update:semver-major' }} # 開発環境向けかつ、メジャーバージョン以外
      - run: |  # 自動承認と自動マージ
          gh pr review "${GITHUB_HEAD_REF}" --approve
          gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
