name: Environment Variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${BRAANCH}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
