name: Artifacts
on:
  push:
jobs:
  updalod:
    runs-on: ubuntu-latest
    steps:
      - run: date > date.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploaded
          path: date.txt
          retention-days: 7
      - run: |
          if [[ -f "${GITHUB_WORKSPACE}/dummy" ]]; then exit 0; fi
          dd if=/dev/urandom of="${GITHUB_WORKSPACE}/dummy" bs=1M count=10
          sleep 30
      - run: ls -lh "${GITHUB_WORKSPACE}/dummy"
  download:
    runs-on: ubuntu-latest
    needs: [updalod]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: uploaded
          path: downloaded
      - run: cat downloaded/date.txt
