name: Add Mask
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PASSWORD: SuperSecret123
    steps:
      - run: echo "::add-mask::${{ env.PASSWORD }}"
      - run: echo "${{ env.PASSWORD }}"
      - run: echo "::add-mask::${PASSWORD}"
      - run: echo "${PASSWORD}"
