name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version to publish example: 1.0.0'
env:
  IMAGE_NAME: 'gha-image'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=v${{ inputs.version }}
            type=raw,value=latest
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: docker/example
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
